version: 2.1

orbs:
  win: circleci/windows@2.2.0

workflows:
  default:
    jobs:
      - build-and-test


jobs:
  build-and-test:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          command: |
            pip install -r requirements-dev.txt
      - run:
          name: Run tests
          command: python -m pytest
